### PR TITLE
Authentication enhancements

### PR DESCRIPTION
**Pull request by martinetd**
Hi,

not quite sure how to contribute as there does not seem to be patches on the mailing list.
I'm starting simple with two small patches:
 - first one just disables local echo for http basic auth password prompt, as I don't like to leave this stuff in my scrollback buffer
 - second one adds an option to enable curl SPNEGO (--negotiate) authentication.
There is a comment around the code that says it has explicitely been disabled, but most of my usage would be around servers which only do gss negotiate.
It would be much simpler to just use CURLAUTH_ANY but as I do not know of any server with the described problem I cannot test if it is still relevant, so a new option seems safer.
This also adds two new messages that I have left in English for Portugese, Polish and Russian as I do not speak these.

Thanks!

### CODE REVIEW

**Comment by CMB** [comment]
Posting patches to the mailing list is fine, but the issue tracker
is also good.

With regard to your second patch, for authentication, we
have the following commit from 2014:

commit bbd9f81242fd3897f94815d7ed25c9c1b7f9996e
Author: Adam Thompson <arthompson1990@gmail.com>
Date:   Mon Aug 11 22:29:57 2014 +0100

    Switch to explicitly specifying which http authentication methods we support
    This fixes a problem where servers offering NTLM also say they offer Negotiate,
    and libcurl doesn't fall back to NTLM when Negotiate auth fails because it
    isn't set up on a user's system. This commit disables Negotiate auth by
    specifying we only want to use the strongest out of basic,
    digest and NTLM authentication methods.

Maybe @arthompson would be able to better comment on your second
patch?

**Comment by eklhad** [comment]
As per the first change, turning echo off, I guess that is consistent with linux/unix when you log in, no echo on password, but,
I use edbrowse all the time to log into all sorts of websites, and the password is there in plain sight.
i1=my_login
i2=my_password
So you're addressing a small concern when there might be a bigger one.
We've talked about the second issue and have no solution.
All you have to do is print the line again, on purpose or by accident:

<my_login> <my_password> <sign in>

And there it is in plain sight.
I could key on input type=password and disable echo, and print stars if that line is reprinted, and we've talked about that,
but does html always reliably set type=password on that tag, or do a lot of pages just say type=text?
We really don't have an answer here.
I say keep your scrollback buffer private.

Also, any attempt to do this, if we choose to do this, should have a separate turn echo on and off function that can be written portably, as edbrowse runs on Windows where there is no termios code.
We have some thinking to do here, but I apreciate your input.
Maybe discuss on the development mailint list.

Karl Dahlke

**Comment by CMB** [comment]
> but does html always reliably set type=password on that tag, or do a lot of pages just say type=text?
> We really don't have an answer here.
> I say keep your scrollback buffer private.

In my experience, HTML does reliably set type=password, and if it
doesn't, that's a bug in the site.
So we could definitely key on the type when printing the line, displaying
stars for the field.  Perfectly reasonable thing to do.

Now what about command entry?  When I do
i1=myusername
i2=mypassword
the password is still up there on the screen in plain sight.
The problem is that we read commands from stdin in line-buffered mode,
and we don't know we're getting a password until the whole line has been
read.  Our command-line parsing / evaluating logic all assumes that we
have the whole command line.  I don't think we'd want to change that,
even if it could be changed.
The only obvious solution might be a separate command, for entering
"private" input.  Call it pi.  So pi2 would let us enter a value into
form field 2 on the current line.
It would disable echo and read one line of input from stdin, stripping
the newline and stuffing the string that was read into the field.
Of course this relies on the user to be smart about how they enter data.

**Comment by martinetd** [comment]
I hadn't thought of login forms, but you are right. I agree that type=password ought to be reliable enough, it is set everywhere I care about at least; if we are going with a "private input" command though we do not actually need to rely on it, as we can simply echo stars everwhere private input is used, and plaintext in the other case.

I also am not familiar with windows "terminal" control, the few times I used unix programs on windows were with msys or cygwin which let me have a terminal that I think could handle termios. What kind of window are windows users using edbrowse in?
I guess it would not be too difficult to have two different set of functions for windows and the rest though, happy with that.

Regarding keeping my scrollback buffer, it usually is- but I have coworkers glancing at my screen often enough and it is not obvious to always clear the buffer after sensitive informations have been entered. I would much rather hide the informations right away if possible.
I've just looked at buffers.c again for how to implement 'pi' and it does not look obvious right away but I will think about it, please tell me if it would be acceptable or if you would rather discuss it on the list first if more people are there.

**Comment by CMB** [comment]
Yes, it might be a good idea to move this to the list.  There might be
a few people over there with opinions who aren't reading this.

**Comment by CMB** [comment]
The current set of patches has been pushed.

**Pull request closed without merging**
